ci: simplify alternative call-convention handling in build workflow (#93)

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -294,6 +294,21 @@ jobs:
                                       )" >> $GITHUB_ENV
           echo "CMAKE_BUILD_EXTRA=$(echo ${CMAKE_BUILD_EXTRA} --config ${{ matrix.build_mode }})" >> $GITHUB_ENV
 
+      - name: Setup alternative default call-convention for msvc
+        if: ${{ matrix.config.compiler_name  == 'msvc' && matrix.config.default_call_convention != '' }}
+        shell: bash
+        run: |
+          # translate default_call_convention to appropriate option
+          if [[ "${{ matrix.config.default_call_convention }}" == 'vectorcall' ]]; then
+            CALL_CONVENTION="/Gv"
+          else
+            echo "Invalid call-convention: ${{ matrix.config.default_call_convention }}"
+            exit 1
+          fi
+          
+          # Do NOT remove the double /, as this will cause trouble during cmake configuration (it somehow expands to C:/Program Files/Git/Gv ???!)
+          echo "CXXFLAGS=$(echo ${CXXFLAGS} /${CALL_CONVENTION})" >> $GITHUB_ENV
+
       - name: Clang libc++ setup
         if: ${{ matrix.config.compiler_name == 'clang' && matrix.config.libcxx == true }}
         shell: bash
@@ -329,14 +344,6 @@ jobs:
           apt-get install -y \
             libc++-${{ matrix.config.compiler_version }}-dev:i386 \
             libc++abi-${{ matrix.config.compiler_version }}-dev:i386
-
-      - name: Setup __vectorcall as default call-convention on msvc
-        if: ${{ matrix.config.compiler_name  == 'msvc' && matrix.config.default_call_convention == 'vectorcall' }}
-        shell: bash
-        # Do NOT remove the double /, as this will cause trouble during cmake configuration (it somehow expands to C:/Program Files/Git/Gv ???!)
-        # But, we will probably run into another issue, when CXXFLAGS happens to be not empty...
-        run: |
-          echo "CXXFLAGS=$(echo ${CXXFLAGS} //Gv)" >> $GITHUB_ENV
 
       - name: Enable Address and Undefined Sanitizer
         if: ${{ matrix.config.asan == true }}
@@ -476,11 +483,7 @@ jobs:
               -j5
 
       # cpptrace
-      # cpptrace doesn't support alternative default call conventions
-      # see: https://github.com/jeremy-rifkin/cpptrace/issues/197
       - name: Configure with cpptrace backend
-        id: config-cpptrace-backend
-        if: ${{matrix.config.default_call_convention == '' }}
         shell: bash
         run: |
           cmake \
@@ -492,7 +495,6 @@ jobs:
               -D MIMICPP_CONFIG_EXPERIMENTAL_USE_CPPTRACE=YES
 
       - name: Build with cpptrace backend
-        if: ${{ steps.config-cpptrace-backend.outcome == 'success' }}
         shell: bash
         run: |
           cmake --build build \
@@ -500,7 +502,6 @@ jobs:
               ${{ env.CMAKE_BUILD_EXTRA }}
 
       - name: Run tests with cpptrace backend
-        if: ${{ steps.config-cpptrace-backend.outcome == 'success' }}
         shell: bash
         env:
           CTEST_OUTPUT_ON_FAILURE: 1
@@ -513,7 +514,8 @@ jobs:
 
       #################################
       # Adapter Tests
-      # Workflow is skipped, when an alternative default call-convention is applied.
+      # Workflow is skipped, when an alternative default call-convention is applied, because not all of these
+      # framework supports it.
       - name: Configure adapter tests
         id: config-adapter-test
         if: ${{ matrix.config.default_call_convention == '' }}
